export interface FomoItem {
  text: string;
  author?: string;
  kind: 'quote' | 'tip';
}

export const FOMO_ITEMS: FomoItem[] = [
  { kind: 'quote', text: 'The stock market is a device for transferring money from the impatient to the patient.', author: 'Warren Buffett' },
  { kind: 'quote', text: 'Be fearful when others are greedy, and greedy when others are fearful.', author: 'Warren Buffett' },
  { kind: 'quote', text: 'The four most expensive words in investing are: "This time it\'s different."', author: 'Sir John Templeton' },
  { kind: 'quote', text: 'Bull markets are born on pessimism, grow on skepticism, mature on optimism, and die on euphoria.', author: 'Sir John Templeton' },
  { kind: 'quote', text: 'In investing, what is comfortable is rarely profitable.', author: 'Robert Arnott' },
  { kind: 'quote', text: 'The market can stay irrational longer than you can stay solvent.', author: 'John Maynard Keynes' },
  { kind: 'quote', text: 'Buy when there\'s blood in the streets, even if the blood is your own.', author: 'Baron Rothschild' },
  { kind: 'quote', text: 'FOMO is the fastest way to turn a good trade into a bad one.', author: 'Anonymous trader wisdom' },
  { kind: 'quote', text: 'You don\'t have to catch every pump. You just have to not blow up.', author: 'Crypto proverb' },
  { kind: 'quote', text: 'It\'s not whether you\'re right or wrong that matters, but how much money you make when you\'re right and how much you lose when you\'re wrong.', author: 'George Soros' },
  { kind: 'quote', text: 'I am always ready to learn although I do not always like being taught.', author: 'Winston Churchill' },
  { kind: 'quote', text: 'Amateurs think about how much money they can make. Professionals think about how much money they could lose.', author: 'Jack Schwager' },
  { kind: 'quote', text: 'The hard part is not finding the trade. It\'s waiting for it.', author: 'Livermore (paraphrased)' },
  { kind: 'quote', text: 'Every time history repeats itself, the price goes up.', author: 'Ronald Wright' },
  { kind: 'quote', text: 'Your worst enemy in a bull market is the fear of missing out. Your worst enemy in a bear market is yourself.', author: 'Anonymous trader wisdom' },
  { kind: 'quote', text: 'HODL is a plan. FOMO is not.', author: 'Crypto proverb' },
  { kind: 'quote', text: 'The best traders are the ones who are comfortable doing nothing.', author: 'Anonymous trader wisdom' },
  { kind: 'quote', text: 'Every mania ends the same way: the last buyer is left holding the bag.', author: 'Anonymous trader wisdom' },
  { kind: 'quote', text: 'Price is what you pay. Value is what you get.', author: 'Warren Buffett' },
  { kind: 'quote', text: 'If you\'re not willing to own a stock for 10 years, don\'t even think about owning it for 10 minutes.', author: 'Warren Buffett' },
  { kind: 'quote', text: 'Euphoria is the most dangerous signal. When even your grandma asks about the coin — it\'s time to leave.', author: 'Anonymous trader wisdom' },
  { kind: 'tip', text: 'Never enter a position because it is pumping. If you missed the move, let it go — there will always be another one.' },
  { kind: 'tip', text: 'Set your entry and exit plan BEFORE you look at the chart. Emotions spike with green candles.' },
  { kind: 'tip', text: 'If you feel urgent pressure to buy RIGHT NOW — that is FOMO. Wait 24 hours before acting.' },
  { kind: 'tip', text: 'Size your positions so that a 50% drop doesn\'t change your life. Then FOMO loses its power.' },
  { kind: 'tip', text: 'Turn off the price alerts. Checking the chart every 5 minutes is how FOMO wins.' },
  { kind: 'tip', text: 'Ask yourself: would I buy this if nobody was talking about it on X right now?' },
  { kind: 'tip', text: 'Follow Smart Money flows, not influencer calls. Data > hype. (That\'s literally this dashboard.)' },
  { kind: 'tip', text: 'Keep a trading journal. Write down WHY you entered. FOMO entries look obvious in hindsight.' },
  { kind: 'tip', text: 'Missing a 10x hurts less than catching a -90%. Asymmetry is on the side of patience.' },
  { kind: 'tip', text: 'The whales profit from your FOMO. Don\'t be exit liquidity — wait for the dust to settle.' },
  { kind: 'tip', text: 'DCA beats panic-buying the top. Boring? Yes. Profitable? Statistically, also yes.' },
  { kind: 'tip', text: 'If the chart already went vertical, the risk/reward is now upside-down. Vertical entries are lottery tickets, not trades.' },
  { kind: 'tip', text: 'A stop-loss is cheaper than therapy for regret.' },
  { kind: 'tip', text: 'Don\'t chase a coin that pumped 200% today. The next trade is always just around the corner.' },
  { kind: 'tip', text: 'The market will be open tomorrow. If you can\'t find a good entry now, wait. FOMO is a liar.' },
  { kind: 'tip', text: 'If you can\'t explain why you bought it in one sentence, you shouldn\'t own it.' },
  { kind: 'tip', text: 'Never increase your position just because it\'s going up. That\'s greed dressed up as conviction.' },
  { kind: 'tip', text: 'When everyone on your feed is suddenly a genius — that\'s the top signal, not the entry point.' },
  { kind: 'tip', text: 'Check the volume, not the hype. A pump without volume is a trap set for FOMO buyers.' },
  { kind: 'tip', text: 'Write down your target price BEFORE you buy. If you don\'t have one, it means you don\'t have a plan.' },
  { kind: 'tip', text: 'The best position size is the one you can sleep with. If you\'re stressed, you\'re overexposed.' },
  { kind: 'tip', text: 'Green candles feel good. Red candles teach lessons. Don\'t let either decide for you.' },
  { kind: 'tip', text: 'Take profits on the way up. The person who "sold too early" usually still made money. The person who waited for the top usually didn\'t.' },
  { kind: 'tip', text: 'If a token is trending #1 on everyone\'s feed, you\'re probably late. The smart money bought quietly weeks ago.' },
  { kind: 'tip', text: 'Your job is not to predict the top. It\'s to not be the one holding it when the music stops.' },
  { kind: 'tip', text: 'Set alerts for your thesis, not for price. "Has anything fundamentally changed?" is a better question than "how high can it go?"' },
];
